### PR TITLE
fix: update operator image values to match chart

### PR DESCRIPTION
**Pull request by anthonywendt**

### CODE REVIEW

**Comment by anthonywendt** [comment]
Latest chart changed the image values structure for some images which broke the air-gap deployment as we are not packaging up the default images it was now trying to use.
https://github.com/rook/rook/blob/bc37caa4624e866e56fb826e84226f3db6308359/deploy/charts/rook-ceph/values.yaml#L480C3-L514C17

There are also these new values that I'm not sure about? Maybe these defaults are okay?
https://github.com/rook/rook/blob/bc37caa4624e866e56fb826e84226f3db6308359/deploy/charts/rook-ceph/values.yaml#L84C1-L85C28
https://github.com/rook/rook/blob/bc37caa4624e866e56fb826e84226f3db6308359/deploy/charts/rook-ceph/values.yaml#L91C1-L94C26

**Review by mjnagel — COMMENTED** [review]
Will also want to update the renovate config, I think the matches currently wouldn't catch the new syntax? It may also be worth adding a basic "test" to check the images being used by pods in the rook-ceph ns and validate they are all coming from Zarf in CI.

**Comment by anthonywendt** [comment]
> Will also want to update the renovate config, I think the matches currently wouldn't catch the new syntax? It may also be worth adding a basic "test" to check the images being used by pods in the rook-ceph ns and validate they are all coming from Zarf in CI.

Added check in test for zarf registry images.
Screenshot 2024-04-16 at 9 40 03 PM

I looked at the renovate config earlier and I think what is there is good?
Considering that [this](https://github.com/defenseunicorns/uds-capability-rook-ceph/blob/cebbeb94bff9d212b2d75e94a37784ed01b7a649/values/operator-values.yaml#L4) tag gets updated, and I think its because of [this](https://github.com/defenseunicorns/uds-capability-rook-ceph/blob/cebbeb94bff9d212b2d75e94a37784ed01b7a649/renovate.json#L46) renovate match config?

I guess I could maybe remove [this](https://github.com/defenseunicorns/uds-capability-rook-ceph/blob/cebbeb94bff9d212b2d75e94a37784ed01b7a649/renovate.json#L45C14-L45C79) now?

**Review by mjnagel — APPROVED** [review]

**Comment by mjnagel** [comment]
@anthonywendt you're totally right, I skimmed over that match earlier but it should work for all of these now 🎉 . Love the test here, will help make sure we don't miss this sort of thing in the future.

**Pull request merged**
